// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYsTx0ybclrej1AEmtgOR3cdm5PlY-0Xc',
    appId: '1:318740104905:android:ef006d4ac94d9746d92f18',
    messagingSenderId: '318740104905',
    projectId: 'myeventapp-611ff',
    storageBucket: 'myeventapp-611ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7aDDODmKaiqyx7zjPRpve1dd8_3biRlw',
    appId: '1:318740104905:ios:73446bf68bf3bac8d92f18',
    messagingSenderId: '318740104905',
    projectId: 'myeventapp-611ff',
    storageBucket: 'myeventapp-611ff.firebasestorage.app',
    androidClientId: '318740104905-9j7njlpoql9g3clomb31ophee7el5a0o.apps.googleusercontent.com',
    iosClientId: '318740104905-mokflsu1vo95dubcl4mlbn46622d60vq.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventlyC17Fri',
  );

}